### ISSUE TITLE
Add OSS License

### ISSUE THREAD

**Issue by bengregori** [ServiceCanada/x-notify#50]
Adding an OSS license like MIT would help clarify legal parameters for other jurisdictions interested in replicating the x-notify system.

**Comment by bengregori** [comment]
Submitted pull request to add MIT license

**Comment by duboisp** [comment]
@bengregori Thank you for submitting the PR

**Comment by bengregori** [comment]
Very happy to! This repo will be featured on my think tank's public respository of government-approved tools/resources that address covid related challenges. We hope that it will improve discoverability of open source tools (we're working with Canadian Open Call as well) Take a look here: https://newamericafoundation.github.io/pandemic-response-repository/
